### ISSUE TITLE
Model Target instability

### ISSUE THREAD

**Issue by valentinptc** [ptcrealitylab/vuforia-spatial-toolbox-ios#35]
The Model Targets seem to not work flawless.
We need to test with a multitude of different models to investigate whats going on.

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/detecting-model-targets-issues/115/5

**Comment by valentinptc** [comment]
Everything seems to be working fine.
