### ISSUE TITLE
Don't break tracker if app pauses unexpectedly

### ISSUE THREAD

**Issue by benptc** [ptcrealitylab/vuforia-spatial-toolbox-ios#5]
E.g. if user swipes control panel from top or bottom of screen, Vuforia tracker pauses or stops completely (not quite sure), so app needs to be restarted.

Make sure to properly account for whether the freeze button is pressed to decide whether to resume the video and tracking when the app opens again after a pause.

**Comment by benptc** [comment]
Vuforia 9 handles this better than previous versions, but we would still benefit from making it work regardless of the freeze button, etc

**Comment by benptc** [comment]
This seems to still be an issue if the phone locks/unlocks or the user switches between apps. We should look into properly pausing/restoring the AR tracking context when the app state changes.

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/issue-in-vst-1-2-3-in-iphone-xr-hangs-frequently/158/4

**Comment by benptc** [comment]
This was fixed with PR #40
