### ISSUE TITLE
startVideoRecording crashes app

### ISSUE THREAD

**Issue by benptc** [ptcrealitylab/vuforia-spatial-toolbox-ios#6]
Fix the video recording frame so this doesn't happen, or at least fails gracefully.

**Comment by benptc** [comment]
This doesn't seem to happen anymore on the devices I'm testing with. Need to determine how to consistently replicate

**Comment by valentinptc** [comment]
Was that fixed by #26 ?

**Comment by benptc** [comment]
Yes! Closing this now
